### ISSUE TITLE
[BUG]Forward compatibility error with NVTabular Criteo preprocessing on Driver 460.73.01

### ISSUE THREAD

**Issue by mengdong** [NVIDIA-Merlin/NVTabular#1170]
**Describe the bug**
Numba error Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR ptxas application ptx input indicates NVtabular lacks in backward compatibility support for A100 Tesla GPU

**Steps/Code to reproduce bug**

follow https://github.com/jarokaz/merlin-on-vertex/tree/main/src/training/dataprep which is based on https://github.com/NVIDIA/NVTabular/blob/main/examples/scaling-criteo/02-ETL-with-NVTabular.ipynb

**Expected behavior**

root@430f7bc912b1:/src# python preprocess.py         --train_folder /criteo_data/criteo_raw_parquet_train         --valid_folder /criteo_data/criteo_raw_parquet_valid         --output_folder /criteo_data/criteo_processed_parquet         --devices 0,1,2,3,4,5,6,7         --protocol tcp         --device_limit_frac 0.8         --device_pool_frac 0.9         --num_io_threads 8         --part_mem_frac 0.08         --out_files_per_proc 8         --freq_limit 6         --shuffle PER_PARTITION
2021-10-07 23:05:56,982 Checking if any device memory is already occupied..
2021-10-07 23:05:57,151 Creating a DASK cluster.
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2021-10-07 23:06:04,128 Creating datasets...
2021-10-07 23:06:08,228 Fitting the workflow
distributed.worker - WARNING - Compute Failed
Function:  _finalize_moments
args:      ({'df-count':            I1          I2          I3          I4          I5          I6          I7          I8          I9         I10         I11         I12         I13
0  4195197692  4195197692  4195197692  4195197692  4195197692  4195197692  4195197692  4195197692  4195197692  4195197692  4195197692  4195197692  4195197692, 'df-sum':              I1            I2            I3            I4            I5            I6           I7            I8            I9           I10           I11           I12           I13
0  1.172157e+11 -2.043947e+11  2.275783e+10  2.824460e+11  5.616660e+10  6.584179e+09  657856188.0 -1.879959e+11  4.071374e+10  1.142936e+09  1.023692e+10 -1.743628e+10  2.829400e+10, 'df2-sum':              I1            I2            I3            I4            I5            I6            I7            I8            I9           I10           I11           I12           I13
0  7.268566e+14  2.456452e+15  4.692377e+11  1.084869e+15  1.775123e+13  1.796412e+12  1.738808e+
kwargs:    {}
Exception: LinkerError("[222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR\nptxas application ptx input, line 9; fatal   : Unsupported .version 7.4; current version is '7.2'")

Traceback (most recent call last):
  File "preprocess.py", line 284, in <module>
    preprocess(args)
  File "preprocess.py", line 119, in preprocess
    workflow.fit(train_dataset)
  File "/nvtabular/nvtabular/workflow/workflow.py", line 227, in fit
    results = [r.result() for r in self.client.compute(stats)]
  File "/nvtabular/nvtabular/workflow/workflow.py", line 227, in <listcomp>
    results = [r.result() for r in self.client.compute(stats)]
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/client.py", line 228, in result
    raise exc.with_traceback(tb)
  File "/nvtabular/nvtabular/ops/moments.py", line 89, in _finalize_moments
    n = inp["df-count"].iloc[0]
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/indexing.py", line 246, in __getitem__
    return self._getitem_tuple_arg(arg)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/indexing.py", line 518, in _getitem_tuple_arg
    df.index = as_index(self._df.index[arg[0]])
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/index.py", line 2958, in as_index
    column.as_column(arbitrary, dtype=kwargs.get("dtype", None)), **kwargs
  File "/usr/local/lib/python3.8/dist-packages/cudf/core/column/column.py", line 1875, in as_column
    utils.scalar_broadcast_to(arbitrary, length, dtype=dtype)
  File "/usr/local/lib/python3.8/dist-packages/cudf/utils/utils.py", line 80, in scalar_broadcast_to
    out_col.data_array_view[:] = scalar
  File "/usr/local/lib/python3.8/dist-packages/numba/cuda/cudadrv/devices.py", line 224, in _require_cuda_context
    return fn(*args, **kws)
  File "/usr/local/lib/python3.8/dist-packages/numba/cuda/cudadrv/devicearray.py", line 572, in __setitem__
    return self._do_setitem(key, value)
  File "/usr/local/lib/python3.8/dist-packages/numba/cuda/cudadrv/devicearray.py", line 630, in _do_setitem
    _assign_kernel(lhs.ndim).forall(n_elements, stream=stream)(lhs, rhs)
  File "/usr/local/lib/python3.8/dist-packages/numba/cuda/compiler.py", line 495, in __call__
    kernel = self.kernel.specialize(*args)
  File "/usr/local/lib/python3.8/dist-packages/numba/cuda/compiler.py", line 1058, in specialize
    specialization = Dispatcher(self.py_func, [types.void(*argtypes)],
  File "/usr/local/lib/python3.8/dist-packages/numba/cuda/compiler.py", line 936, in __init__
    self.compile(sigs[0])
  File "/usr/local/lib/python3.8/dist-packages/numba/cuda/compiler.py", line 1115, in compile
    kernel.bind()
  File "/usr/local/lib/python3.8/dist-packages/numba/cuda/compiler.py", line 626, in bind
    self._codelibrary.get_cufunc()
  File "/usr/local/lib/python3.8/dist-packages/numba/cuda/codegen.py", line 201, in get_cufunc
    cubin = self.get_cubin(cc=device.compute_capability)
  File "/usr/local/lib/python3.8/dist-packages/numba/cuda/codegen.py", line 174, in get_cubin
    linker.add_ptx(ptx.encode())
  File "/usr/local/lib/python3.8/dist-packages/numba/cuda/cudadrv/driver.py", line 2190, in add_ptx
    raise LinkerError("%s\n%s" % (e, self.error_log))
numba.cuda.cudadrv.driver.LinkerError: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR
ptxas application ptx input, line 9; fatal   : Unsupported .version 7.4; current version is '7.2'
distributed.core - ERROR - Exception while handling op register-client
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/core.py", line 502, in handle_comm
    result = await result
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 5194, in add_client
    self.remove_client(client=client)
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 5221, in remove_client
    self.client_releases_keys(
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 4961, in client_releases_keys
    self.transitions(recommendations)
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 6975, in transitions
    self.send_all(client_msgs, worker_msgs)
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 5478, in send_all
    w = stream_comms[worker]
KeyError: 'tcp://127.0.0.1:33347'
tornado.application - ERROR - Exception in callback functools.partial(<function TCPServer._handle_connection.<locals>.<lambda> at 0x7f5b66a51f70>, <Task finished name='Task-71' coro=<BaseTCPListener._handle_stream() done, defined at /root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/comm/tcp.py:478> exception=KeyError('tcp://127.0.0.1:33347')>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.8/dist-packages/tornado/tcpserver.py", line 331, in <lambda>
    gen.convert_yielded(future), lambda f: f.result()
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/comm/tcp.py", line 495, in _handle_stream
    await self.comm_handler(comm)
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/core.py", line 502, in handle_comm
    result = await result
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 5194, in add_client
    self.remove_client(client=client)
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 5221, in remove_client
    self.client_releases_keys(
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 4961, in client_releases_keys
    self.transitions(recommendations)
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 6975, in transitions
    self.send_all(client_msgs, worker_msgs)
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 5478, in send_all
    w = stream_comms[worker]
KeyError: 'tcp://127.0.0.1:33347'

**Environment details (please complete the following information):**
 GCP - A2-highgpu-8g - nvcr.io/nvidia/merlin/merlin-training:21.09
 Driver: NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2

**Comment by mengdong** [comment]
Hi Ben, thanks for your explanation. I want to let you know that at least on GCP, GKE runs on driver v460, Vertex runs on driver v460, this means only option to deploy the container is on GCE.

**Comment by mengdong** [comment]
Confirmed with Vertex that they can run preprocessing successfully with `nvcr.io/nvidia/merlin/merlin-training:21.09`, the previous error is from a non-DLFW based container. Thank you Ben for investigating. I will close the bug now.
