### ISSUE TITLE
[BUG] scaling-criteo example raise a "key error" in transform valid_dataset

### ISSUE THREAD

**Issue by kunlunl** [NVIDIA-Merlin/NVTabular#1268]
**Describe the bug**
I'm running the scaling-criteo example in https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/scaling-criteo/02-ETL-with-NVTabular.ipynb, everything is working well until I meet the `workflow.transform(valid_dataset).to_parquet(...)`, it raise a key error of "C1", while the transform of train_dataset has no problem.

**Steps/Code to reproduce bug**
I'm following the example of https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/scaling-criteo/02-ETL-with-NVTabular.ipynb, the only difference between my code and the example is:
* `categorify_op = Categorify(out_path=stats_path, max_size=num_buckets)` (in example)==>  `categorify_op = Categorify(out_path=stats_path, freq_threshold=3)` (in my code) 

**Expected behavior**
I think the transform of valid_dataset should be the same as train_dataset.

**Environment details (please complete the following information):**
 - Environment location: Docker
 - Method of NVTabular install: Docker
   - (If method of install is [Docker], provide `docker pull` & `docker run` commands used)
   - `docker run --gpus=all -it --rm nvcr.io/nvidia/merlin/merlin-tensorflow-training:21.11`
 

**Additional context**
I'm using a machine with  8 Tesla V100

The output log:
```
num_days: 24
train_paths: ['../raid_tmp/output/criteo/day_0.parquet', '../raid_tmp/output/criteo/day_1.parquet', '../raid_tmp/output/criteo/day_2.parquet', '../raid_tmp/output/criteo/day_3.parquet', '../raid_tmp/output/criteo/day_4.parquet', '../raid_tmp/output/criteo/day_5.parquet', '../raid_tmp/output/criteo/day_6.parquet', '../raid_tmp/output/criteo/day_7.parquet', '../raid_tmp/output/criteo/day_8.parquet', '../raid_tmp/output/criteo/day_9.parquet', '../raid_tmp/output/criteo/day_10.parquet', '../raid_tmp/output/criteo/day_11.parquet', '../raid_tmp/output/criteo/day_12.parquet', '../raid_tmp/output/criteo/day_13.parquet', '../raid_tmp/output/criteo/day_14.parquet', '../raid_tmp/output/criteo/day_15.parquet', '../raid_tmp/output/criteo/day_16.parquet', '../raid_tmp/output/criteo/day_17.parquet', '../raid_tmp/output/criteo/day_18.parquet', '../raid_tmp/output/criteo/day_19.parquet', '../raid_tmp/output/criteo/day_20.parquet', '../raid_tmp/output/criteo/day_21.parquet', '../raid_tmp/output/criteo/day_22.parquet']
valid_paths: ['../raid_tmp/output/criteo/day_23.parquet']
device_size: 15.78173828125 GB
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
<Client: 'tcp://127.0.0.1:33167' processes=8 threads=8, memory=503.79 GiB>
start workflow.fit(train_dataset) ...
/usr/local/lib/python3.8/dist-packages/numba/cuda/compiler.py:865: NumbaPerformanceWarning: Grid size (1) < 2 * SM count (160) will likely result in GPU under utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
finished. run time: 147.56 s
start workflow.transform(train_dataset) ...
finished. run time: 258.69 s
start workflow.transform(valid_dataset) ...
distributed.worker - WARNING - Compute Failed
Function:  _write_subgraph
args:      (<nvtabular.io.dask.DaskSubgraph object at 0x7f65d400af40>, ('part_7.parquet',), '../raid_tmp/output/processed/valid/', None, <fsspec.implementations.local.LocalFileSystem object at 0x7f6719c865e0>, ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13', 'C14', 'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21', 'C22', 'C23', 'C24', 'C25', 'C26'], ['I1', 'I2', 'I3', 'I4', 'I5', 'I6', 'I7', 'I8', 'I9', 'I10', 'I11', 'I12', 'I13'], ['label'], 'parquet', 0, False, '')
kwargs:    {}
Exception: KeyError('C1')

Traceback (most recent call last):
  File "2.py", line 138, in <module>
    workflow.transform(valid_dataset).to_parquet(
  File "/nvtabular/nvtabular/io/dataset.py", line 886, in to_parquet
    _ddf_to_dataset(
  File "/nvtabular/nvtabular/io/dask.py", line 369, in _ddf_to_dataset
    out = client.compute(out).result()
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/client.py", line 228, in result
    raise exc.with_traceback(tb)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/nvtabular/nvtabular/io/dask.py", line 210, in _write_subgraph
    return writer.close()
  File "/nvtabular/nvtabular/io/writer.py", line 314, in close
    _general_meta = self.package_general_metadata()
  File "/nvtabular/nvtabular/io/writer.py", line 253, in package_general_metadata
    data["cats"].append({"col_name": c, "index": self.col_idx[c]})
KeyError: 'C1'
FATAL: exception not rethrown
FATAL: exception not rethrown
FATAL: exception not rethrown
FATAL: exception not rethrown
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
distributed.core - ERROR - Exception while handling op register-client
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/core.py", line 502, in handle_comm
    result = await result
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 5194, in add_client
    self.remove_client(client=client)
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 5221, in remove_client
    self.client_releases_keys(
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 4961, in client_releases_keys
    self.transitions(recommendations)
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 6975, in transitions
    self.send_all(client_msgs, worker_msgs)
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 5478, in send_all
    w = stream_comms[worker]
KeyError: 'tcp://127.0.0.1:46683'
tornado.application - ERROR - Exception in callback functools.partial(<function TCPServer._handle_connection.<locals>.<lambda> at 0x7f7705cf30d0>, <Task finished name='Task-71' coro=<BaseTCPListener._handle_stream() done, defined at /root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/comm/tcp.py:478> exception=KeyError('tcp://127.0.0.1:46683')>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.8/dist-packages/tornado/tcpserver.py", line 331, in <lambda>
    gen.convert_yielded(future), lambda f: f.result()
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/comm/tcp.py", line 495, in _handle_stream
    await self.comm_handler(comm)
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/core.py", line 502, in handle_comm
    result = await result
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 5194, in add_client
    self.remove_client(client=client)
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 5221, in remove_client
    self.client_releases_keys(
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 4961, in client_releases_keys
    self.transitions(recommendations)
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 6975, in transitions
    self.send_all(client_msgs, worker_msgs)
  File "/root/.local/lib/python3.8/site-packages/distributed-2021.7.1-py3.8.egg/distributed/scheduler.py", line 5478, in send_all
    w = stream_comms[worker]
KeyError: 'tcp://127.0.0.1:46683'
Exception in thread AsyncProcess Dask Worker process (from Nanny) watch process join:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner

```

**Comment by kunlunl** [comment]
For reference, my code is as below:
```
import os
import re
import shutil
import warnings
import time
import argparse

import numpy as np
from dask_cuda import LocalCUDACluster
from dask.distributed import Client

import nvtabular as nvt
from nvtabular.ops import (
    Categorify,
    Clip,
    FillMissing,
    Normalize
)
from nvtabular.utils import _pynvml_mem_size, device_mem_size


if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('--input_path', type=str, help='Where day_*.parquet are saved.')
    parser.add_argument('--output_path', type=str)
    parser.add_argument('--gpus', type=int)
    parser.add_argument('--freq_limit', type=int, default=3)
    parser.add_argument('--input_prefix', type=str, default='day_')
    parser.add_argument('--dask_space', type=str, default='./dask_space/')
    parser.add_argument('--protocol', type=str, default='tcp')
    parser.add_argument('--dashboard_port', type=str, default='8787')
    parser.add_argument('--train_output_files', type=int, default=-1)
    args = parser.parse_args()

    INPUT_DATA_DIR = args.input_path
    OUTPUT_DATA_DIR = args.output_path
    stats_path = os.path.join(OUTPUT_DATA_DIR, 'stats/')
    dask_workdir = args.dask_space

    if os.path.isdir(dask_workdir):
        shutil.rmtree(dask_workdir)
    os.makedirs(dask_workdir)

    if os.path.isdir(OUTPUT_DATA_DIR):
        shutil.rmtree(OUTPUT_DATA_DIR)
    os.makedirs(OUTPUT_DATA_DIR)

    fname = args.input_prefix + '{}.parquet'
    num_days = len(
        [i for i in os.listdir(INPUT_DATA_DIR) if re.match(fname.format('[0-9]{1,2}'), i) is not None]
    )
    print('num_days:', num_days)

    train_paths = [os.path.join(INPUT_DATA_DIR, fname.format(day)) for day in range(num_days - 1)]
    valid_paths = [os.path.join(INPUT_DATA_DIR, fname.format(num_days - 1))]
    print('train_paths:', train_paths)
    print('valid_paths:', valid_paths)

    dashboard_port = args.dashboard_port
    protocol = args.protocol
    NUM_GPUS = [i for i in range(args.gpus)]
    visible_devices = ','.join([str(n) for n in NUM_GPUS])
    device_limit_frac = 0.9
    device_pool_frac = 0.95
    part_mem_frac = 0.15

    device_size = device_mem_size(kind='total')
    print('device_size:', device_size / 1024 / 1024 / 1024, 'GB')

    device_limit = int(device_limit_frac * device_size)
    device_pool_size = int(device_pool_frac * device_size)
    part_size = int(part_mem_frac * device_size)

    for dev in visible_devices.split(','):
        fmem = _pynvml_mem_size(kind='free', index=int(dev))
        used = (device_size - fmem) / 1e9
        if used > 1.0:
            print(f'{used} GB is already occupied on device {int(dev)}')
            exit()

    cluster = LocalCUDACluster(
        protocol=protocol,
        n_workers=len(visible_devices.split(',')),
        CUDA_VISIBLE_DEVICES=visible_devices,
        device_memory_limit=device_limit,
        local_directory=dask_workdir,
        dashboard_address=':' + dashboard_port,
        rmm_pool_size=(device_pool_size // 256) * 256
    )

    client = Client(cluster)
    print(client)

    CONTINUOUS_COLUMNS = ['I' + str(x) for x in range(1, 14)]
    CATEGORICAL_COLUMNS = ['C' + str(x) for x in range(1, 27)]
    LABEL_COLUMNS = ['label']
    COLUMNS = CONTINUOUS_COLUMNS + CATEGORICAL_COLUMNS + LABEL_COLUMNS

    #num_buckets = 10000000
    #categorify_op = Categorify(out_path=stats_path, max_size=num_buckets)
    categorify_op = Categorify(out_path=stats_path, freq_threshold=args.freq_limit)
    cat_features = CATEGORICAL_COLUMNS >> categorify_op
    cont_features = CONTINUOUS_COLUMNS >> FillMissing() >> Clip(min_value=0) >> Normalize()
    features = cat_features + cont_features + LABEL_COLUMNS

    workflow = nvt.Workflow(features, client=client)

    dict_dtypes = {}
    for col in CATEGORICAL_COLUMNS:
        dict_dtypes[col] = np.int64
    for col in CONTINUOUS_COLUMNS:
        dict_dtypes[col] = np.float32
    for col in LABEL_COLUMNS:
        dict_dtypes[col] = np.float32

    train_dataset = nvt.Dataset(train_paths, engine='parquet', part_size=part_size)
    valid_dataset = nvt.Dataset(valid_paths, engine='parquet', part_size=part_size)
    output_train_dir = os.path.join(OUTPUT_DATA_DIR, 'train/')
    output_valid_dir = os.path.join(OUTPUT_DATA_DIR, 'valid/')
    os.makedirs(output_train_dir)
    os.makedirs(output_valid_dir)

    print('start workflow.fit(train_dataset) ...')
    runtime = time.time()
    workflow.fit(train_dataset)
    runtime = time.time() - runtime
    print('finished. run time: %.2f s'%(runtime))

    workflow.save(os.path.join(OUTPUT_DATA_DIR, 'workflow'))

    print('start workflow.transform(train_dataset) ...')
    runtime = time.time()
    workflow.transform(train_dataset).to_parquet(
        output_files=len(NUM_GPUS) if args.train_output_files == -1 else args.train_output_files,
        output_path=output_train_dir,
        shuffle=nvt.io.Shuffle.PER_PARTITION,
        dtypes=dict_dtypes,
        cats=CATEGORICAL_COLUMNS,
        conts=CONTINUOUS_COLUMNS,
        labels=LABEL_COLUMNS
    )
    runtime = time.time() - runtime
    print('finished. run time: %.2f s'%(runtime))

    print('start workflow.transform(valid_dataset) ...')
    runtime = time.time()
    workflow.transform(valid_dataset).to_parquet(
        output_path=output_valid_dir,
        dtypes=dict_dtypes,
        cats=CATEGORICAL_COLUMNS,
        conts=CONTINUOUS_COLUMNS,
        labels=LABEL_COLUMNS
    )
    runtime = time.time() - runtime
    print('finished. run time: %.2f s'%(runtime))

```

**Comment by EvenOldridge** [comment]
@jperez999 could this be related to subgraph changes.

**Comment by EvenOldridge** [comment]
Possibly related to: https://github.com/NVIDIA-Merlin/NVTabular/issues/1284 and the file creation on parquet side...

**Comment by jperez999** [comment]
I have verified it is the same issue.
