### ISSUE TITLE
[BUG] Cannot Replicate single node multi gpu Movielens Tensorflow example

### ISSUE THREAD

**Issue by dragarok** [NVIDIA-Merlin/NVTabular#1274]
**Describe the bug**
So, I have setup horovod, nvtabular and tensorflow using conda on sagemaker. Tested environment with horovod examples which run fine with multi GPU. I cannot replicate the example from nvtabular's multi GPU example with horovod.

**Steps/Code to reproduce bug**
Horovod Info:
> Horovod v0.23.0:
> 
> Available Frameworks:
>     [X] TensorFlow
>     [X] PyTorch
>     [ ] MXNet
> 
> Available Controllers:
>     [X] MPI
>     [X] Gloo
> 
> Available Tensor Operations:
>     [X] NCCL
>     [ ] DDL
>     [ ] CCL
>     [X] MPI
>     [X] Gloo
> 
Nvtabular: 0.7.1
Horovod build command: 
`HOROVOD_CUDA_HOME=/usr/local/cuda-11.0 HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod`

**Environment details (please complete the following information):**
 - Environment location: [Sagemaker g4dn.12xlarge
 - Method of NVTabular install: conda [Can provide full conda environment spec if required.]
 

**Additional context**
Also pipeline runs great when with single worker.
ETL working perfectly with NVTabular. Everything works great except the last line of the example where this command is there:
`!horovodrun -np 2 sh hvd_wrapper.sh python tf_trainer.py --dir_in $BASE_DIR --batch_size 16384`

**I am new to multi GPU stuff. Any direction or help will be really helpful.**

```
2021-11-26 01:57:21.875286: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
[1,0]<stderr>:2021-11-26 01:57:25.067064: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
[1,1]<stderr>:2021-11-26 01:57:25.068022: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
[1,0]<stderr>:2021-11-26 01:57:26.479664: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
[1,0]<stderr>:2021-11-26 01:57:26.479771: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
[1,0]<stderr>:2021-11-26 01:57:26.479915: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,0]<stderr>:2021-11-26 01:57:26.480859: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
[1,0]<stderr>:pciBusID: 0000:00:1b.0 name: Tesla T4 computeCapability: 7.5
[1,0]<stderr>:coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
[1,0]<stderr>:2021-11-26 01:57:26.480898: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
[1,0]<stderr>:2021-11-26 01:57:26.480945: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
[1,0]<stderr>:2021-11-26 01:57:26.480968: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
[1,0]<stderr>:2021-11-26 01:57:26.481001: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
[1,0]<stderr>:2021-11-26 01:57:26.481031: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
[1,0]<stderr>:2021-11-26 01:57:26.481056: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
[1,0]<stderr>:2021-11-26 01:57:26.481078: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
[1,0]<stderr>:2021-11-26 01:57:26.481102: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
[1,0]<stderr>:2021-11-26 01:57:26.481155: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,0]<stderr>:2021-11-26 01:57:26.482213: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,0]<stderr>:2021-11-26 01:57:26.483021: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
[1,1]<stderr>:2021-11-26 01:57:26.486900: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
[1,1]<stderr>:2021-11-26 01:57:26.487013: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
[1,1]<stderr>:2021-11-26 01:57:26.487115: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,1]<stderr>:2021-11-26 01:57:26.488053: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
[1,1]<stderr>:pciBusID: 0000:00:1c.0 name: Tesla T4 computeCapability: 7.5
[1,1]<stderr>:coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
[1,1]<stderr>:2021-11-26 01:57:26.488075: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
[1,1]<stderr>:2021-11-26 01:57:26.488123: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
[1,1]<stderr>:2021-11-26 01:57:26.488146: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
[1,1]<stderr>:2021-11-26 01:57:26.488179: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
[1,1]<stderr>:2021-11-26 01:57:26.488204: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
[1,1]<stderr>:2021-11-26 01:57:26.488228: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
[1,1]<stderr>:2021-11-26 01:57:26.488250: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
[1,1]<stderr>:2021-11-26 01:57:26.488275: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
[1,1]<stderr>:2021-11-26 01:57:26.488321: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,1]<stderr>:2021-11-26 01:57:26.489181: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,1]<stderr>:2021-11-26 01:57:26.489987: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
[1,0]<stderr>:2021-11-26 01:57:28.461853: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
[1,0]<stderr>:To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[1,0]<stderr>:2021-11-26 01:57:28.464250: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
[1,0]<stderr>:2021-11-26 01:57:28.464366: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,0]<stderr>:2021-11-26 01:57:28.465294: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
[1,0]<stderr>:pciBusID: 0000:00:1b.0 name: Tesla T4 computeCapability: 7.5
[1,0]<stderr>:coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
[1,0]<stderr>:2021-11-26 01:57:28.465364: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
[1,0]<stderr>:2021-11-26 01:57:28.465377: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
[1,0]<stderr>:2021-11-26 01:57:28.465388: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
[1,0]<stderr>:2021-11-26 01:57:28.465410: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
[1,0]<stderr>:2021-11-26 01:57:28.465422: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
[1,0]<stderr>:2021-11-26 01:57:28.465431: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
[1,0]<stderr>:2021-11-26 01:57:28.465441: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
[1,0]<stderr>:2021-11-26 01:57:28.465453: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
[1,0]<stderr>:2021-11-26 01:57:28.465502: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,0]<stderr>:2021-11-26 01:57:28.466328: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,0]<stderr>:2021-11-26 01:57:28.467121: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
[1,0]<stderr>:2021-11-26 01:57:28.467172: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
[1,0]<stderr>:2021-11-26 01:57:28.467307: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
[1,0]<stderr>:2021-11-26 01:57:28.467317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
[1,0]<stderr>:2021-11-26 01:57:28.467323: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
[1,0]<stderr>:2021-11-26 01:57:28.467382: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,0]<stderr>:2021-11-26 01:57:28.468232: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,0]<stderr>:2021-11-26 01:57:28.469080: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,0]<stderr>:2021-11-26 01:57:28.469904: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3021 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:1b.0, compute capability: 7.5)
[1,1]<stderr>:2021-11-26 01:57:28.479048: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
[1,1]<stderr>:To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[1,1]<stderr>:2021-11-26 01:57:28.481709: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
[1,1]<stderr>:2021-11-26 01:57:28.481814: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,1]<stderr>:2021-11-26 01:57:28.482671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
[1,1]<stderr>:pciBusID: 0000:00:1c.0 name: Tesla T4 computeCapability: 7.5
[1,1]<stderr>:coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
[1,1]<stderr>:2021-11-26 01:57:28.482740: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
[1,1]<stderr>:2021-11-26 01:57:28.482753: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
[1,1]<stderr>:2021-11-26 01:57:28.482764: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
[1,1]<stderr>:2021-11-26 01:57:28.482787: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
[1,1]<stderr>:2021-11-26 01:57:28.482799: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
[1,1]<stderr>:2021-11-26 01:57:28.482809: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
[1,1]<stderr>:2021-11-26 01:57:28.482819: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
[1,1]<stderr>:2021-11-26 01:57:28.482831: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
[1,1]<stderr>:2021-11-26 01:57:28.482875: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,1]<stderr>:2021-11-26 01:57:28.483700: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,1]<stderr>:2021-11-26 01:57:28.484544: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
[1,1]<stderr>:2021-11-26 01:57:28.484583: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
[1,1]<stderr>:2021-11-26 01:57:28.484714: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
[1,1]<stderr>:2021-11-26 01:57:28.484724: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
[1,1]<stderr>:2021-11-26 01:57:28.484730: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
[1,1]<stderr>:2021-11-26 01:57:28.484785: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,1]<stderr>:2021-11-26 01:57:28.485674: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,1]<stderr>:2021-11-26 01:57:28.486498: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[1,1]<stderr>:2021-11-26 01:57:28.487308: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3021 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:1c.0, compute capability: 7.5)
[1,1]<stderr>:2021-11-26 01:57:32.060871: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
[1,1]<stderr>:2021-11-26 01:57:32.089086: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2499995000 Hz
[1,0]<stderr>:2021-11-26 01:57:32.163555: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
[1,0]<stderr>:2021-11-26 01:57:32.173764: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2499995000 Hz
[1,1]<stderr>:2021-11-26 01:57:32.211344: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
[1,0]<stderr>:2021-11-26 01:57:32.297343: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
[1,1]<stderr>:2021-11-26 01:57:32.727974: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
[1,0]<stderr>:2021-11-26 01:57:32.813470: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.11
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "tf_trainer.py", line 138, in <module>
[1,1]<stderr>:    loss_value = training_step(examples, labels, batch == 0)
[1,1]<stderr>:  File "/home/ec2-user/SageMaker/.persisted_conda/horovod2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
[1,1]<stderr>:    result = self._call(*args, **kwds)
[1,1]<stderr>:  File "/home/ec2-user/SageMaker/.persisted_conda/horovod2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 888, in _call
[1,1]<stderr>:    return self._stateless_fn(*args, **kwds)
[1,1]<stderr>:  File "/home/ec2-user/SageMaker/.persisted_conda/horovod2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2943, in __call__
[1,1]<stderr>:    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
[1,1]<stderr>:  File "/home/ec2-user/SageMaker/.persisted_conda/horovod2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
[1,1]<stderr>:    ctx, args, cancellation_manager=cancellation_manager))
[1,1]<stderr>:  File "/home/ec2-user/SageMaker/.persisted_conda/horovod2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 560, in call
[1,1]<stderr>:    ctx=ctx)
[1,1]<stderr>:  File "/home/ec2-user/SageMaker/.persisted_conda/horovod2/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
[1,1]<stderr>:    inputs, attrs, num_outputs)
[1,1]<stderr>:tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
[1,1]<stderr>:  (0) Unknown:  ncclCommInitRank failed: unhandled cuda error
[1,1]<stderr>:	 [[{{node DistributedGradientTape_Allreduce/cond_10/then/_99/DistributedGradientTape_Allreduce/cond_10/HorovodAllreduce_gradient_tape_model_dense_3_BiasAdd_BiasAddGrad_0}}]]
[1,1]<stderr>:	 [[HorovodBroadcast_dense_features_userId_embedding_weights_0/ReadVariableOp/_162]]
[1,1]<stderr>:  (1) Unknown:  ncclCommInitRank failed: unhandled cuda error
[1,1]<stderr>:	 [[{{node DistributedGradientTape_Allreduce/cond_10/then/_99/DistributedGradientTape_Allreduce/cond_10/HorovodAllreduce_gradient_tape_model_dense_3_BiasAdd_BiasAddGrad_0}}]]
[1,1]<stderr>:0 successful operations.
[1,1]<stderr>:0 derived errors ignored. [Op:__inference_training_step_9977]
[1,1]<stderr>:
[1,1]<stderr>:Function call stack:
[1,1]<stderr>:training_step -> training_step
[1,1]<stderr>:
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "tf_trainer.py", line 138, in <module>
[1,0]<stderr>:    loss_value = training_step(examples, labels, batch == 0)
[1,0]<stderr>:  File "/home/ec2-user/SageMaker/.persisted_conda/horovod2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
[1,0]<stderr>:    result = self._call(*args, **kwds)
[1,0]<stderr>:  File "/home/ec2-user/SageMaker/.persisted_conda/horovod2/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 888, in _call
[1,0]<stderr>:    return self._stateless_fn(*args, **kwds)
[1,0]<stderr>:  File "/home/ec2-user/SageMaker/.persisted_conda/horovod2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2943, in __call__
[1,0]<stderr>:    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
[1,0]<stderr>:  File "/home/ec2-user/SageMaker/.persisted_conda/horovod2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
[1,0]<stderr>:    ctx, args, cancellation_manager=cancellation_manager))
[1,0]<stderr>:  File "/home/ec2-user/SageMaker/.persisted_conda/horovod2/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 560, in call
[1,0]<stderr>:    ctx=ctx)
[1,0]<stderr>:  File "/home/ec2-user/SageMaker/.persisted_conda/horovod2/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
[1,0]<stderr>:    inputs, attrs, num_outputs)
[1,0]<stderr>:tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
[1,0]<stderr>:  (0) Unknown:  ncclCommInitRank failed: unhandled cuda error
[1,0]<stderr>:	 [[{{node DistributedGradientTape_Allreduce/cond_10/then/_99/DistributedGradientTape_Allreduce/cond_10/HorovodAllreduce_gradient_tape_model_dense_3_BiasAdd_BiasAddGrad_0}}]]
[1,0]<stderr>:	 [[HorovodBroadcast_dense_2_kernel_0/ReadVariableOp/_132]]
[1,0]<stderr>:  (1) Unknown:  ncclCommInitRank failed: unhandled cuda error
[1,0]<stderr>:	 [[{{node DistributedGradientTape_Allreduce/cond_10/then/_99/DistributedGradientTape_Allreduce/cond_10/HorovodAllreduce_gradient_tape_model_dense_3_BiasAdd_BiasAddGrad_0}}]]
[1,0]<stderr>:0 successful operations.
[1,0]<stderr>:0 derived errors ignored. [Op:__inference_training_step_12181]
[1,0]<stderr>:
[1,0]<stderr>:Function call stack:
[1,0]<stderr>:training_step -> training_step
[1,0]<stderr>:
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[10201,1],1]
  Exit code:    1
--------------------------------------------------------------------------

```

**Comment by dragarok** [comment]
For me: It was how I built horovod.
`HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_BROADCAST=NCCL HOROVOD_NCCL_LINK=SHARED pip install --no-cache-dir horovod`
This build of horovod works great if you have conda installation. Will be glad if this helps anyone.
