### ISSUE TITLE
[BUG] LambdaOp doesn't work on the raw lambda functions (it expects the lambda function to have a "create_node" attribute)

### ISSUE THREAD

**Issue by Arnie0426** [NVIDIA-Merlin/NVTabular#1520]
**Describe the bug**
LambdaOps don't work in the latest merlin (following the example in the docs)

**Steps/Code to reproduce bug**
https://nvidia-merlin.github.io/NVTabular/main/api/ops/lambdaop.html?highlight=lambdaop#nvtabular.ops.LambdaOp
The example usage 1 doesn't work and throws an error.
```
lambda_feature = nvt.ColumnSelector(["col1"])
new_lambda_feature = lambda_feature >> (lambda col: col.str.slice(0, 5))
```

```
AttributeError                            Traceback (most recent call last)
Input In [48], in <cell line: 2>()
      1 lambda_feature = nvt.ColumnSelector(["col1"])
----> 2 new_lambda_feature = lambda_feature >> (lambda col: col.str.slice(0, 5))

File /core/merlin/dag/selector.py:128, in ColumnSelector.__rshift__(self, operator)
    124 if isinstance(operator, type) and issubclass(operator, merlin.dag.BaseOperator):
    125     # handle case where an operator class is passed
    126     operator = operator()
--> 128 return operator.create_node(self) >> operator

AttributeError: 'function' object has no attribute 'create_node'
```

You can hack around it by adding an `nvt.ops.LambdaOp()` in front of your lambda function like:
```
new_lambda_feature = lambda_feature >> nvt.ops.LambdaOp(lambda col: col.str.slice(0, 5))
```

But this also causes issues in case you want to use a column to generate a new column with a different dtype - a common usecase could be something like changing datetime types into hour/day/timestamp.

Example:

```
datetime_col = nvt.ColumnSelector(["time"])  # time is a datetime64[ns] column
ts = datetime_col >> nvt.ops.LambdaOp(lambda col: cudf.to_datetime(col).astype(np.int64) // 10 ** 9) >> nvt.ops.Rename(postfix="_timestamp")

w = nvt.Workflow(datetime_col + ts)
w.fit(train_set)
dataset = w.transform(train_set)

```

But when you try to see the data inside, you get errors like:
```
Failed to transform operator <nvtabular.ops.lambdaop.LambdaOp object at 0x7f7def8be9a0>
Traceback (most recent call last):
  File "/nvtabular/nvtabular/workflow/workflow.py", line 539, in _transform_partition
    f"Dtype discrepancy detected for column {col_name}: "
  File "/nvtabular/nvtabular/ops/lambdaop.py", line 103, in label
    source = getsourcelines(self.f)[0][0]
  File "/opt/conda/lib/python3.8/inspect.py", line 979, in getsourcelines
    lines, lnum = findsource(object)
  File "/opt/conda/lib/python3.8/inspect.py", line 798, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
distributed.worker - WARNING - Compute Failed
Function:  subgraph_callable-6e8e2068-b78f-42f9-9cc0-26e2684b
args:      ([{'piece': ('part-00000-1ab1f599-3eb8-4f9c-aa2c-cffe70690c00-c000.snappy.parquet', [0], [])}])
kwargs:    {}
Exception: "OSError('could not get source code')"

```

**Comment by Arnie0426** [comment]
nvt.ops.LambdaOp expects the dtype of the columns to be the same.

Another way to reproduce the error:

```
def extract_hour(col):
    return col.dt.hour

ts = datetime_col >> nvt.ops.LambdaOp(extract_hour) >> nvt.ops.Rename(postfix="_hour")

w = nvt.Workflow(datetime_col + ts)
w.fit(train_set)
dataset = w.transform(train_set)
dataset.head()
```

```
Failed to transform operator <nvtabular.ops.lambdaop.LambdaOp object at 0x7f5c3deec5e0>
Traceback (most recent call last):
  File "/nvtabular/nvtabular/workflow/workflow.py", line 538, in _transform_partition
    raise TypeError(
TypeError: Dtype discrepancy detected for column start_time: operator extract_hour reported dtype `datetime64[ns]` but returned dtype `int16`.
distributed.worker - WARNING - Compute Failed
Function:  subgraph_callable-8f598a98-5178-43af-a40d-c78da1ad
args:      ([{'piece': (part-00000-1ab1f599-3eb8-4f9c-aa2c-cffe70690c00-c000.snappy.parquet', [0], [])}])
kwargs:    {}
Exception: "TypeError('Dtype discrepancy detected for column start_time: operator extract_hour reported dtype `datetime64[ns]` but returned dtype `int16`.')"
```

**Comment by rnyak** [comment]
@Arnie0426 thanks reporting the error and sorry for the inconvenience. we do not use lambda op as 

```
lambda_feature >> (lambda col: col.str.slice(0, 5))
```
Correct, it is used as `nvt.ops.LambdaOp(lambda col: col.str.slice(0, 5))`.  

we need to update example usage of the LambdaOp in the docs yes. And I will check your repro example as well.

@mikemckiernan  fyi.

**Comment by karlhigley** [comment]
You can change the output dtype by supplying the `dtype` property when creating the LambdaOp:

```python
nvt.ops.LambdaOp(extract_hour, dtype=np.int32)
```

(It looks like the docstrings for this operator need an update.)

**Comment by Arnie0426** [comment]
Thanks =) Passing a dtype solved it.
