### ISSUE TITLE
[BUG]  pynvml.nvml.NVMLError_FunctionNotFound: Function Not Found when deploying a DASK cluster for preprocessing with CUDA 11.0

### ISSUE THREAD

**Issue by shashank3959** [NVIDIA-Merlin/NVTabular#1601]
**Describe the bug**
A "pynvml.nvml.NVMLError_FunctionNotFound: Function Not Found" error is observed when deploying a distributed DASK cluster on a system with CUDA 11.0, specifically running the following command 
`client = Client(cluster)`

Trace

`
Unable to start CUDA Context
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pynvml/nvml.py", line 782, in _nvmlGetFunctionPointer
    _nvmlGetFunctionPointer_cache[name] = getattr(nvmlLib, name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1: undefined symbol: nvmlDeviceGetComputeRunningProcesses_v2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dask_cuda/initialize.py", line 42, in _create_cuda_context
    ctx = has_cuda_context()
  File "/usr/local/lib/python3.8/dist-packages/distributed/diagnostics/nvml.py", line 78, in has_cuda_context
    running_processes = pynvml.nvmlDeviceGetComputeRunningProcesses_v2(handle)
  File "/usr/local/lib/python3.8/dist-packages/pynvml/nvml.py", line 2191, in nvmlDeviceGetComputeRunningProcesses_v2
    fn = _nvmlGetFunctionPointer("nvmlDeviceGetComputeRunningProcesses_v2")
  File "/usr/local/lib/python3.8/dist-packages/pynvml/nvml.py", line 785, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_FUNCTION_NOT_FOUND)
pynvml.nvml.NVMLError_FunctionNotFound: Function Not Found
Unable to start CUDA Context
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pynvml/nvml.py", line 782, in _nvmlGetFunctionPointer
    _nvmlGetFunctionPointer_cache[name] = getattr(nvmlLib, name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1: undefined symbol: nvmlDeviceGetComputeRunningProcesses_v2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dask_cuda/initialize.py", line 42, in _create_cuda_context
    ctx = has_cuda_context()
  File "/usr/local/lib/python3.8/dist-packages/distributed/diagnostics/nvml.py", line 78, in has_cuda_context
    running_processes = pynvml.nvmlDeviceGetComputeRunningProcesses_v2(handle)
  File "/usr/local/lib/python3.8/dist-packages/pynvml/nvml.py", line 2191, in nvmlDeviceGetComputeRunningProcesses_v2
    fn = _nvmlGetFunctionPointer("nvmlDeviceGetComputeRunningProcesses_v2")
  File "/usr/local/lib/python3.8/dist-packages/pynvml/nvml.py", line 785, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_FUNCTION_NOT_FOUND)
pynvml.nvml.NVMLError_FunctionNotFound: Function Not Found
`

**Steps/Code to reproduce bug**
Follow this notebook https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/scaling-criteo/02-ETL-with-NVTabular.ipynb on a system with the below specification

**Expected behavior**
No error when deploying a dask cluster

**Environment details (please complete the following information):**
 - Environment location: Docker; 
 - Method of NVTabular install: Docker; Merlin-tensorflow-training:22.05
- GPU Hardware: V100-32GB
- CUDA Version: 11.0
- NVIDIA Driver: 450.51.06

**Additional context**
Currently, the [README](https://github.com/NVIDIA-Merlin/NVTabular) mentions that CUDA versions 11.0+ are supported. I suspect the CUDA version is an issue, since I didn't observe this on systems with CUDA 11.4 & 11.5.

**Comment by pentschev** [comment]
Hi @shashank3959 , this is actually because the CUDA runtime binaries being used (specifically `libnvidia-ml.so.1`) are from CUDA 11.2, which requires `nvmlDeviceGetComputeRunningProcesses_v2` that only exists in CUDA 11.2+. Could you confirm what `cudatookit` you have installed by running `conda list cudatoolkit`? I think you have `cudatoolkit>=11.2` and may be able to resolve that issue by using a Docker container that is built with `cudatoolkit=11.0`.

**Comment by pentschev** [comment]
For future reference, CUDA Enhanced Compatibility requires driver >=450.80.02, in which case the docker container above should work. For older drivers, such as the one currently in use, they would need builds with the specific CUDA version being request, in this case CUDA 11.0.

**Comment by shashank3959** [comment]
Thanks @pentschev, yes I had a slightly older version of the driver in the system when I tried the sample.
