### ISSUE TITLE
[BUG] chunkwise_moment, infinite recursion, dask_cuda proxy_object

### ISSUE THREAD

**Issue by lmartinpierrat** [NVIDIA-Merlin/NVTabular#1629]
**Describe the bug**
My workflow started crashing when I applied it to a different dataset, and I am not sure what the difference is yet

Here are the logs of the dask_cuda worker: 

```
Exception ignored in: <function ProxyObject.__del__ at 0x7f1818096040>
Traceback (most recent call last):
  File "miniconda3/envs/nvtabular_cu116_py39/lib/python3.9/site-packages/dask_cuda/proxy_object.py", line 377, in __del__
    pxy = self._pxy_get()
  File "miniconda3/envs/nvtabular_cu116_py39/lib/python3.9/site-packages/dask_cuda/proxy_object.py", line 368, in _pxy_get
    return self._pxy_detail
  File "miniconda3/envs/nvtabular_cu116_py39/lib/python3.9/site-packages/dask_cuda/proxy_object.py", line 452, in __getattr__
    return self._pxy_detail
  File "miniconda3/envs/nvtabular_cu116_py39/lib/python3.9/site-packages/dask_cuda/proxy_object.py", line 452, in __getattr__
    pxy = self._pxy_get()
  File "miniconda3/envs/nvtabular_cu116_py39/lib/python3.9/site-packages/dask_cuda/proxy_object.py", line 368, in _pxy_get
    pxy = self._pxy_get()
  File "miniconda3/envs/nvtabular_cu116_py39/lib/python3.9/site-packages/dask_cuda/proxy_object.py", line 368, in _pxy_get
  File "miniconda3/envs/nvtabular_cu116_py39/lib/python3.9/site-packages/dask_cuda/proxy_object.py", line 368, in _pxy_get
    return self._pxy_detail
  File "miniconda3/envs/nvtabular_cu116_py39/lib/python3.9/site-packages/dask_cuda/proxy_object.py", line 452, in __getattr__
    return self._pxy_detail
[...]
RecursionError: maximum recursion depth exceeded
2022-07-21 02:16:07,477 - distributed.worker - WARNING - Compute Failed
Key:       ('chunkwise-moments-274ce31877c1fdfb439b559e1518a9d2', 17, 0)
Function:  _chunkwise_moments
args:      (<dask_cuda.proxy_object.ProxyObject at 0x7f178072fd60 of cudf.core.dataframe.DataFrame at 0x7f178071d9d0>)
kwargs:    {}
Exception: 'TypeError("__init__() missing 1 required positional argument: \'detail\'")'
```

python code logs
```
Traceback (most recent call last):
  File "preprocessing.py", line 92, in <module>
    main()
  File "preprocessing.py", line 65, in main
    processed = workflow.fit_transform(dataset)
  File "miniconda3/envs/nvtabular_cu116_py39/lib/python3.9/site-packages/nvtabular/workflow/workflow.py", line 286, in fit_transform
    self.fit(dataset)
  File "miniconda3/envs/nvtabular_cu116_py39/lib/python3.9/site-packages/nvtabular/workflow/workflow.py", line 245, in fit
    results = [r.result() for r in dask_client.compute(stats)]
  File "miniconda3/envs/nvtabular_cu116_py39/lib/python3.9/site-packages/nvtabular/workflow/workflow.py", line 245, in <listcomp>
    results = [r.result() for r in dask_client.compute(stats)]
  File "miniconda3/envs/nvtabular_cu116_py39/lib/python3.9/site-packages/distributed/client.py", line 282, in result
    raise exc.with_traceback(tb)
  File "miniconda3/envs/nvtabular_cu116_py39/lib/python3.9/site-packages/nvtabular/ops/moments.py", line 67, in _chunkwise_moments
    vals = {name: type(df)() for name in ["count", "sum", "squaredsum"]}
  File "miniconda3/envs/nvtabular_cu116_py39/lib/python3.9/site-packages/nvtabular/ops/moments.py", line 67, in <dictcomp>
    vals = {name: type(df)() for name in ["count", "sum", "squaredsum"]}
TypeError: __init__() missing 1 required positional argument: 'detail'

```

**Steps/Code to reproduce bug**
TBD, I am unsure what trigger the issue since it is dataset related.

**Expected behavior**
Either not crash or tell me what's wrong more clearly

**Environment details (please complete the following information):**
GCS with conda

```
name: nvtabular_cu116_py39
channels:
 - rapidsai
 - nvidia
 - pytorch
 - conda-forge
 - defaults
dependencies:
 - python=3.9
 - cudatoolkit=11.6
 - nvtabular
 - jupyterlab
 - pytorch
 - torchvision
 - torchaudio
 - cupy
 - cudf
 - scipy
 - dask
 - dask-cudf
 - dask-cuda
 - ucx-proc=*=gpu
 - ucx
 - ucx-py
```

**Additional context**
I will update the issue if I have more details, resolve it if I find my problem.

**Comment by lmartinpierrat** [comment]
Nevermind, it seems that the only issue I have is that since the dataset is bigger, and that I activated --jit-unspill on my dask-cuda-worker, it blew up somewhere.

I can provide a reproducible example if someone is interested in finding the underlying issue, but my resolution will be to remove the jit-unspill
