### ISSUE TITLE
[BUG] Memory errors multi-GPU Categorify with default setting

### ISSUE THREAD

**Issue by rjzamora** [NVIDIA-Merlin/NVTabular#1695]
**Describe the bug**

When running the [multi-gpu criteo benchmark](https://github.com/NVIDIA-Merlin/NVTabular/blob/main/bench/examples/dask-nvtabular-criteo-benchmark.py) on a full DGX-1 system (8x32GB V100 GPUs). I get errors similar to the following with otherwise default options:

```
2022-10-28 18:08:32,583 - distributed.worker - ERROR - Unable to allocate 1.04 TiB for an array with shape (1138166333439,) and data type uint8
Traceback (most recent call last):
  File "/code/merlin-debug/distributed/distributed/worker.py", line 3274, in gather_dep
    response = await get_data_from_worker(
  File "/code/merlin-debug/distributed/distributed/worker.py", line 4590, in get_data_from_worker
    return await retry_operation(_get_data, operation="get_data_from_worker")
  File "/code/merlin-debug/distributed/distributed/utils_comm.py", line 381, in retry_operation
    return await retry(
  File "/code/merlin-debug/distributed/distributed/utils_comm.py", line 366, in retry
    return await coro()
  File "/code/merlin-debug/distributed/distributed/worker.py", line 4570, in _get_data
    response = await send_recv(
  File "/code/merlin-debug/distributed/distributed/core.py", line 739, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/code/merlin-debug/distributed/distributed/comm/tcp.py", line 229, in read
    frames = host_array(frames_nbytes)
  File "/code/merlin-debug/distributed/distributed/comm/utils.py", line 30, in numpy_host_array
    return numpy.empty((n,), dtype="u1").data
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 1.04 TiB for an array with shape (1138166333439,) and data type uint8
```

Note that this benchmark has other bugs that will prevent it from running "as is." However, I will submit a separate issue/fix for that.

**Environment details:**
Using [merlin-pytorch 22.10 container](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/merlin/containers/merlin-pytorch)

**Comment by rjzamora** [comment]
This is a bug in `distributed-22.05.1` that causes errors in the serialization/deserialization of large pyarrow objects. For example, the following script will fail for `distributed-22.05.1`, but will succeed for `distributed-22.05.2`:

```python
import pyarrow as pa
from dask.delayed import Delayed
import numpy as np

from dask.distributed import LocalCluster
from dask.distributed import Client

n_workers = 8
npartitions = 10
partition_len = 4_000_000  # Needs to be large enough (2m works)

def make_data(i):
    # Create large table
    return pa.Table.from_arrays(
        [
            pa.array([i] * partition_len),
            # Note: Fails without using numpy or string data as well
            pa.array(["a", "b", "c", "d"] * int(partition_len / 4)),
            pa.array(np.arange(partition_len, dtype="int")),
            pa.array(np.arange(partition_len, dtype="float")),
        ],
        names = ["x", "y", "z", "w"],
    )

def choose_table(tables):
    # Return one of the tables
    return tables[0]

def make_delayed_table():
    # Build toy dask graph for delayed pyarrow table
    name = "my-table"
    dsk = {
        (name + "-collection", i): (make_data, i)
        for i in range(npartitions)
    }
    dsk[name] = (choose_table, list(dsk.keys()))
    return Delayed(name, dsk)

if __name__ == "__main__":
    client = Client(LocalCluster(n_workers=n_workers))
    print(make_delayed_table().compute())
```

The only way to avoid this issue is to update to a newer version of `distributed` or to use `Categorify(..., on_host=False)`.
