### ISSUE TITLE
[BUG] nvtabular never registered with registry torch.dataloader_loader while using transformers4rec

### ISSUE THREAD

**Issue by gunesevitan** [NVIDIA-Merlin/NVTabular#1713]
**Describe the bug**
I encountered this error while trying to replicate training pipeline of transformers4rec and I couldn't find anything about this.

```
Traceback (most recent call last):
  File "/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/src/transformers4rec_modules/train.py", line 56, in <module>
    trainer.train()
  File "/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/venv/lib/python3.10/site-packages/transformers/trainer.py", line 1203, in train
    train_dataloader = self.get_train_dataloader()
  File "/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/venv/lib/python3.10/site-packages/transformers4rec/torch/trainer.py", line 156, in get_train_dataloader
    return T4RecDataLoader.parse(self.args.data_loader_engine).from_schema(
  File "/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/venv/lib/python3.10/site-packages/transformers4rec/torch/utils/data_utils.py", line 53, in parse
    return dataloader_registry.parse(class_or_str)
  File "/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/venv/lib/python3.10/site-packages/merlin_standard_lib/registry.py", line 265, in parse
    return self[class_or_str]
  File "/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/venv/lib/python3.10/site-packages/merlin_standard_lib/registry.py", line 232, in __getitem__
    raise KeyError(
KeyError: 'nvtabular never registered with registry torch.dataloader_loader. Available:\n     pyarrow:\n      * pyarrow\n      * pyarrow_builder'
```

**Steps/Code to reproduce bug**
Two modules are required to replicate this behavior. First one is model.py

```
from transformers4rec import torch as tr
from transformers4rec.config import transformer
from transformers4rec.torch.ranking_metric import RecallAt


def get_model(
        schema, max_sequence_length, d_output, masking,
        transformer_model_class, transformer_model_args,
        mlp_dimensions,
):
    """
    Create model with specified parameters

    Parameters
    ----------
    schema: merlin_standard_lib.schema.schema.Schema
        Dataset schema

    max_sequence_length: int
        Maximum length of sequences

    d_output: int
        Projection module dimensions

    masking: str
        Masking type applied input embeddings

    transformer_model_class: str
        Transformer model class available in transformer module

    transformer_model_args: dict
        Keyword arguments passed transformer_model_class.build method

    mlp_dimensions: int
        MLP block dimensions

    Returns
    -------
    model: transformers4rec.torch.model.base.Model
        Created model object
    """

    inputs = tr.TabularSequenceFeatures.from_schema(
        schema,
        max_sequence_length=max_sequence_length,
        d_output=d_output,
        masking=masking,
    )

    transformer_model = getattr(transformer, transformer_model_class)
    transformer_config = transformer_model.build(**transformer_model_args)

    body = tr.SequentialBlock(
        inputs,
        tr.MLPBlock(dimensions=mlp_dimensions),
        tr.TransformerBlock(transformer_config, masking=inputs.masking)
    )

    metrics = [
        RecallAt(top_ks=[20], labels_onehot=True)
    ]

    head = tr.Head(
        body,
        tr.NextItemPredictionTask(weight_tying=True, hf_format=True, metrics=metrics),
        inputs=inputs,
    )

    model = tr.Model(head)
    return model
```

and train.py

```
import sys
import yaml
from merlin_standard_lib import Schema
from transformers4rec.config.trainer import T4RecTrainingArguments
from transformers4rec.torch import Trainer

sys.path.append('..')
import settings
from model import get_model


if __name__ == '__main__':

    config = yaml.load(open(settings.MODELS / 'transformers4rec' / 'config.yaml', 'r'), Loader=yaml.FullLoader)
    schema = Schema().from_proto_text(settings.MODELS / 'transformers4rec' / 'schema.pb')

    model = get_model(
        schema=schema,
        **config['model']
    )

    training_arguments = T4RecTrainingArguments(
        output_dir=settings.MODELS / 'transformers4rec',
        overwrite_output_dir=False,
        evaluation_strategy='steps',
        per_device_train_batch_size=config['training']['per_device_train_batch_size'],
        per_device_eval_batch_size=config['training']['per_device_eval_batch_size'],
        gradient_accumulation_steps=config['training']['gradient_accumulation_steps'],
        learning_rate=config['training']['learning_rate'],
        weight_decay=config['training']['weight_decay'],
        max_grad_norm=config['training']['max_grad_norm'],
        num_train_epochs=config['training']['num_train_epochs'],
        lr_scheduler_type=config['training']['lr_scheduler_type'],
        warmup_ratio=config['training']['warmup_ratio'],
        warmup_steps=config['training']['warmup_steps'],
        logging_strategy='steps',
        logging_first_step=1,
        logging_steps=100,
        data_loader_engine='nvtabular',
        dataloader_drop_last=False,
        save_strategy='epoch',
        save_total_limit=1,
        eval_steps=config['training']['eval_steps'],
        dataloader_num_workers=config['training']['dataloader_num_workers'],
        max_sequence_length=500,
        report_to=[],
        no_cuda=False,
    )

    trainer = Trainer(
        model=model,
        args=training_arguments,
        schema=schema,
        compute_metrics=True,
    )
    trainer.train_dataset_or_path = sorted(glob.glob(str(settings.DATA / 'parquet_dataset' / 'train_*.parquet')))
    trainer.eval_dataset_or_path = sorted(glob.glob(str(settings.DATA / 'parquet_dataset' / 'val.parquet')))
    trainer.train()
    trainer._save_model_and_checkpoint(save_model_class=True)
```
trainer.train_dataset_or_path looks good.
```
>>> trainer.train_dataset_or_path
['/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_0.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_1.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_10.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_11.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_12.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_13.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_14.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_15.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_16.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_17.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_18.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_19.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_2.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_20.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_21.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_22.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_23.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_24.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_25.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_26.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_27.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_28.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_29.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_3.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_30.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_31.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_32.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_33.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_34.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_35.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_36.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_37.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_38.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_39.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_4.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_40.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_41.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_42.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_43.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_44.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_45.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_46.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_47.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_48.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_49.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_5.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_50.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_51.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_52.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_53.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_54.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_55.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_6.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_7.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_8.parquet', '/home/gunes/Desktop/Kaggle/otto-multi-objective-recommender-system/data/parquet_dataset/train_9.parquet']
```

I'm also sharing my yaml and pb file for convenience.

schema.pb
```
feature {
  name: "aid"
  type: INT
  int_domain {
    name: "aid"
    min: 0
    max: 1855610
    is_categorical: true
  }
  annotation {
    tag: "item_id"
    tag: "list"
    tag: "categorical"
    tag: "item"
  }
  value_count {
    min: 2
    max: 500
  }
}

feature {
  name: "target"
  type: INT
  int_domain {
    name: "target"
    min: 1
    max: 3
    is_categorical: true
  }
  annotation {
    tag: "list"
    tag: "categorical"
    tag: "item"
  }
  value_count {
    min: 2
    max: 500
  }
}
```

config.yaml
```
model:
  max_sequence_length: 500
  d_output: 100
  masking: 'mlm'
  transformer_model_class: 'XLNetConfig'
  transformer_model_args:
    d_model: 64
    n_head: 4
    n_layer: 2
    total_seq_length: 500
  mlp_dimensions: 64

training:
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 64
  gradient_accumulation_steps: 1
  learning_rate: 0.0001
  weight_decay: 0
  max_grad_norm: 1.0
  num_train_epochs: 5
  lr_scheduler_type: cosine
  warmup_ratio: 0.0
  warmup_steps: 0
  eval_steps: 100
  dataloader_num_workers: 4
```

**Expected behavior**
I'm actually trying to implement this notebook in my local machine so the expected behavior can be seen here.
https://www.kaggle.com/code/theoviel/pretraining-with-merlin-s-transformers4rec

**Environment details**
 - Environment location: Local
 - Method of NVTabular install: `pip install transformers4rec[pytorch,nvtabular]`
 - nvtabular version: 1.5.0
 - torch version: 1.13.0+cu117
 - transformers4rec version: 0.1.15
 - CUDA version 11.7
 - OS: Ubuntu 22.04

**Comment by sararb** [comment]
@gunesevitan, thank you for reporting this bug. In fact, using `pip install transformers4rec[pytorch,nvtabular]` will install the CPU version of `nvtabular`  while T4Rec is expecting the GPU version one. So the error raised in T4Rec is related to the fact that nvtabular dataloader is not defined by T4Rec as it was not able to detect the GPU dependencies. 

 - If you want to run your model on CPU, you should use  the `pyarrow` dataloader instead: `data_loader_engine="pyarrow"`

- The recommended way to use the GPU version of nvtabular is to install T4Rec via `conda` using the following command : `conda install -c nvidia -c conda-forge transformers4rec`

Note that the upcoming release of transformers4rec will include the following changes:

- The nvtabular data loader was migrated to a separate package `merlin-dataloader` : so the pip install will be updated to `pip install transformers4rec[pytorch,nvtabular,dataloader]` 

- T4Rec will support the CPU-version of merlin-dataloader. So you will be able to run the code with the parameter`data_loader_engine="merlin_dataloader"`, for both environments `cpu` and `gpu`

**Comment by rnyak** [comment]
@gunesevitan hello. does the respond above solve your issue? if yes, can we close this ticket? thanks.
