### ISSUE TITLE
[BUG] Training TwoTowerModel when loading dataset using `part_size=128MB` crashes

### ISSUE THREAD

**Issue by mats-claassen** [NVIDIA-Merlin/NVTabular#1785]
**Describe the bug**
I am trying to train a TwoTowerModel. I load the datasets (train and val) using NVTabular.Dataset and later pass them to `model.fit`. When I add the `part_size="128MB"` to the Dataset instantiation call, then model training will crash. If I remove that it works (unless the dataset is too big and I get OOM). I am not sure if this is a bug in NVTabular or in the Merlin models implementation. 

Loading datasets:
```python
    train_ds = Dataset(os.path.join(data_folder, "train", "*.parquet"), part_size="128MB")
    valid_ds = Dataset(os.path.join(data_folder, "valid", "*.parquet"), part_size="128MB")
```

The crash log looks like:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/src/train.py", line 99, in <module>
    train(config, tracker, data_folder, args.models_folder)
  File "/app/src/train.py", line 65, in train
    model.fit(train_ds, validation_data=valid_ds, batch_size=config['train_config']['batch_size'],
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/models/base.py", line 969, in fit
    out = super().fit(**fit_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/models/base.py", line 1262, in call
    outputs, context = self._call_child(block, outputs, context)
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/models/base.py", line 1291, in _call_child
    outputs = call_layer(child, inputs, **call_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/utils/tf_utils.py", line 437, in call_layer
    return layer(inputs, *args, **filtered_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/core/tabular.py", line 478, in _tabular_call
    outputs = self.super().__call__(inputs, *args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/config/schema.py", line 58, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/core/combinators.py", line 566, in call
    out = call_layer(layer, layer_inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/utils/tf_utils.py", line 437, in call_layer
    return layer(inputs, *args, **filtered_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/config/schema.py", line 58, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/models/base.py", line 139, in call
    outputs = call_layer(self.block, inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/utils/tf_utils.py", line 437, in call_layer
    return layer(inputs, *args, **filtered_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/config/schema.py", line 58, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/core/combinators.py", line 269, in call
    return call_sequentially(self.layers, inputs, training=training, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/core/combinators.py", line 836, in call_sequentially
    outputs = call_layer(layer, outputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/utils/tf_utils.py", line 437, in call_layer
    return layer(inputs, *args, **filtered_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/core/tabular.py", line 478, in _tabular_call
    outputs = self.super().__call__(inputs, *args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/config/schema.py", line 58, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/core/combinators.py", line 566, in call
    out = call_layer(layer, layer_inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/utils/tf_utils.py", line 437, in call_layer
    return layer(inputs, *args, **filtered_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/core/tabular.py", line 478, in _tabular_call
    outputs = self.super().__call__(inputs, *args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/config/schema.py", line 58, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/inputs/embedding.py", line 874, in call
    embedded_outputs[name] = self.lookup_feature(name, val)
  File "/usr/local/lib/python3.8/dist-packages/merlin/models/tf/inputs/embedding.py", line 900, in lookup_feature
    out = tf.nn.safe_embedding_lookup_sparse(table_var, val, None, combiner=table.combiner)
ValueError: Exception encountered when calling layer "embedding_features_1" "                 f"(type EmbeddingFeatures).

Dimensions 27825 and 1 are not compatible

Call arguments received by layer "embedding_features_1" "                 f"(type EmbeddingFeatures):
  • inputs={'X_ids': '<tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7fa8fe2f1ca0>'}
  • kwargs={'training': 'False', 'testing': 'False', 'features': {'X_ids': ('tf.Tensor(shape=(27825, 1), dtype=int32)', 'tf.Tensor(shape=(512, 1), dtype=int32)')}}
```

The error is slightly different on each run but still similar.

I also got similar errors when storing the NVTabular dataset into multiple parquet files (using `.to_parquet(..., out_files_per_proc=X`). 
The error to happen only when using multi-hot columns.

**Steps/Code to reproduce bug**
I don't have a small reproducible example right now.

**Expected behavior**
I would expect the model to train no matter in how many files the dataset is split or whether I set the `part_size` parameter of NVTabular.Dataset or not

**Environment details (please complete the following information):**

- Environment location: Docker
- Method of NVTabular install: Docker
  - docker pull: nvcr.io/nvidia/merlin/merlin-tensorflow:22.12 
  - I then install some additional dependencies such as: clearml, jupyterlab, PyYAML
  - docker run --rm -it -d --ipc=host --gpus=all -p 8889:8888 -e CUDA_VISIBLE_DEVICES=0 -v $PWD:/app/ <image_name>

**Comment by rnyak** [comment]
@mats-claassen can you give us more info?

- what dataset are you using? the datasets we provide in our examples or this is your custom dataset?

- what's the size of your train set? is it a single parquet file or it consists of multiple parquet files? if your parquet file size consists of one row group and if it is row group memory size large then you might have OOM issues. in that case you can repartition your train parquet file or reset the number of row group size in your parquet file and save it back to disk. Note that  row group memory size should be smaller than `part_size` arg. Please refer to this [doc](https://nvidia-merlin.github.io/NVTabular/main/resources/troubleshooting.html) for more info.

-  what GPU are you using and what's its memory?
