### ISSUE TITLE
[BUG] Multi-GPU Criteo/DLRM Benchmark not on DGX

### ISSUE THREAD

**Issue by PerkzZheng** [NVIDIA-Merlin/NVTabular#351]
**Describe the bug**
I was doing Multi-GPU Criteo/DLRM Benchmark on 4 GPUs (V100, V100s, P4, T4). Setting device-pool-frac to be 0.2 to make sure the pool size will not exceed P4's maximum memory. 
There is an error about `pyarrow.lib.ArrowInvalid: Buffer #0 too small in array of type string and length`

Also, I am wondering is there any better methods for re-initializing RMM pool size for each GPU separately, and then `client.run(_rmm_pool)`

**Steps/Code to reproduce bug**
`python3 NVT-preproc-standard.py --data-path  '/workdir/NVT-input/temp-output-dask/temp-parquet-after-feature-crossing/' --out-path '/workdir/NVT-input/temp-output-standard' --devices "0,1,2,3" --device-pool-frac 0.2`

**Environment details (please complete the following information):**
 - Environment location: NGC-NVTabular 0.2 Docker
 - Method of NVTabular install: `docker pull nvcr.io/nvidia/nvtabular:0.2`
 - GPUs: V100, V100s, T4, P4
 - device-pool-frac: 0.2

**Additional context**
```
Traceback (most recent call last): 
  File "NVT-preproc-standard.py", line 347, in <module>
    main(parse_args()) 
  File "NVT-preproc-standard.py", line 170, in main
    output_path=output_path,
  File "/nvtabular/nvtabular/workflow.py", line 734, in apply
    num_io_threads=num_io_threads,
  File "/nvtabular/nvtabular/workflow.py", line 832, in build_and_process_graph
    self.exec_phase(idx, record_stats=record_stats)
  File "/nvtabular/nvtabular/workflow.py", line 632, in exec_phase
    computed_stats, op = r.result()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/client.py", line 225, in result
    raise exc.with_traceback(tb)
  File "/opt/conda/envs/rapids/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/nvtabular/nvtabular/ops/categorify.py", line 375, in _top_level_groupby
    output[k] = split.to_pandas()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/dataframe.py", line 4686, in to_pandas
    out_data[i] = self._data[col_key].to_pandas(index=out_index) 
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/column/column.py", line 128, in to_pandas
    pd_series = self.to_arrow().to_pandas(**kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/column/string.py", line 4617, in to_arrow
    len(self), obuf, sbuf, nbuf, self.null_count
  File "pyarrow/array.pxi", line 1807, in pyarrow.lib.StringArray.from_buffers
  File "pyarrow/array.pxi", line 871, in pyarrow.lib.Array.from_buffers
  File "pyarrow/array.pxi", line 1168, in pyarrow.lib.Array.validate
  File "pyarrow/error.pxi", line 85, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Buffer #0 too small in array of type string and length 352919: expected at least 44115 byte(s), got 11072
```

**Comment by rjzamora** [comment]
If you are having trouble setting a "normal" pool size (>=50%), there may be a problem with dask-cuda or rmm.  I wouldn't expect a smaller pool size to help with OOM errors, but I could be wrong.

Note that the multi-gpu criteo/DLRM benchmark was designed with 32GB V100s in mind, and was only tested on 16GB+.  For smaller GPUs, you may need to use a smaller `--part-mem-frac` option (down to 0.1 or less), and you may need to reduce `--device-limit-frac` (down to 0.75 or less).  Are you running into problems with 16GB?

The trouble with the smaller GPUs is likely to be with the categorical encoding.  Although it the limitations *can* be addressed in the future, this transformation currently requires us to temporaritly hold a significant amount of data in device memory for each categorical column.

**Comment by PerkzZheng** [comment]
Yes, one of my 4 gpus are just 8GB memory size. 
I guess I missed the impact of `device-limit-fract` and `part-mem-frac`, and I will try more on those settings.  
Thanks! I will update it after I got more test results.

**Comment by viswa-nvidia** [comment]
retiring this bug
